server.port=28852
management.endpoints.web.exposure.include=health,info
management.endpoint.shutdown.enabled=false
logging.level.org.springframework.web=INFO
logging.level.account=INFO
spring.datasource.url=jdbc:h2:file:../service_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always